"""Create a small hand-authored demo SpriteBundle."""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from spritelab.codec.bundle import SpriteBundle, SpriteMetadata
from spritelab.codec.io import save_bundle
from spritelab.codec.roles import ColorRole


def build_demo_bundle() -> SpriteBundle:
    """Build a simple diamond sprite with five visible colors."""

    alpha = np.zeros((32, 32), dtype=np.uint8)
    index_map = np.zeros((32, 32), dtype=np.uint8)
    role_map = np.full((32, 32), int(ColorRole.TRANSPARENT), dtype=np.uint8)

    palette = np.array(
        [
            [0, 0, 0],  # dummy transparent slot
            [34, 32, 52],  # outline
            [69, 40, 60],  # shadow
            [130, 76, 98],  # midtone
            [238, 195, 154],  # highlight
            [91, 192, 235],  # accent
        ],
        dtype=np.uint8,
    )

    center_x = 16
    center_y = 16
    radius = 10

    for y in range(32):
        for x in range(32):
            distance = abs(x - center_x) + abs(y - center_y)
            if distance <= radius:
                alpha[y, x] = 1

                if distance == radius:
                    index_map[y, x] = 1
                    role_map[y, x] = int(ColorRole.OUTLINE)
                elif y > center_y + 3:
                    index_map[y, x] = 2
                    role_map[y, x] = int(ColorRole.SHADOW)
                elif y < center_y - 3:
                    index_map[y, x] = 4
                    role_map[y, x] = int(ColorRole.HIGHLIGHT)
                else:
                    index_map[y, x] = 3
                    role_map[y, x] = int(ColorRole.MIDTONE)

    for x in range(13, 20):
        if alpha[16, x] == 1:
            index_map[16, x] = 5
            role_map[16, x] = int(ColorRole.ACCENT)

    metadata = SpriteMetadata(
        id="demo_diamond",
        category="demo",
        subtype="diamond",
        caption="A small hand-authored diamond sprite.",
        prompt="manual demo sprite",
        source="examples/create_demo_bundle.py",
        license="CC0-1.0",
        palette_size=int(palette.shape[0] - 1),
        quality_score=1.0,
        extra={"notes": "Generated by the milestone 1 demo script."},
    )

    return SpriteBundle(
        alpha=alpha,
        palette=palette,
        index_map=index_map,
        role_map=role_map,
        metadata=metadata,
    )


def main() -> None:
    bundle = build_demo_bundle()
    save_bundle(bundle, ROOT / "outputs" / "demo_bundle")


if __name__ == "__main__":
    main()
