"""Flexible local and hosted vision-provider hub."""

from spritelab.product_features.providers.adapters import (
    OLLAMA_DEFAULT_ENDPOINT,
    DeterministicMockVisionProvider,
    OllamaVisionProvider,
    OpenAICompatibleVisionProvider,
    PluginVisionProviderAdapter,
    UnavailableVisionProvider,
)
from spritelab.product_features.providers.config import ProviderSettings
from spritelab.product_features.providers.contracts import (
    BatchResponse,
    DiscoveryState,
    ImageInput,
    ImageLabelResult,
    LabelRequest,
    LabelState,
    ModelValidation,
    NormalizedLabel,
    PrivacyClass,
    PrivacyPolicy,
    ProbeResult,
    ProviderHealth,
    ProviderKind,
    ProviderMode,
    ProviderModel,
    RequestEstimate,
    VisionCapabilities,
    VisionProvider,
)
from spritelab.product_features.providers.discovery import (
    PLUGIN_ENTRY_POINT_GROUP,
    DiscoveredProvider,
    VisionProviderRegistry,
)
from spritelab.product_features.providers.errors import (
    ProviderCancelledError,
    ProviderDeadlineExceededError,
    ProviderError,
    ProviderInvalidOutputError,
    ProviderPolicyError,
    ProviderTimeoutError,
)
from spritelab.product_features.providers.hub import (
    HubRunResult,
    ProviderRequestAttempt,
    RetryPolicy,
    VisionProviderHub,
)

__all__ = [
    "OLLAMA_DEFAULT_ENDPOINT",
    "PLUGIN_ENTRY_POINT_GROUP",
    "BatchResponse",
    "DeterministicMockVisionProvider",
    "DiscoveredProvider",
    "DiscoveryState",
    "HubRunResult",
    "ImageInput",
    "ImageLabelResult",
    "LabelRequest",
    "LabelState",
    "ModelValidation",
    "NormalizedLabel",
    "OllamaVisionProvider",
    "OpenAICompatibleVisionProvider",
    "PluginVisionProviderAdapter",
    "PrivacyClass",
    "PrivacyPolicy",
    "ProbeResult",
    "ProviderCancelledError",
    "ProviderDeadlineExceededError",
    "ProviderError",
    "ProviderHealth",
    "ProviderInvalidOutputError",
    "ProviderKind",
    "ProviderMode",
    "ProviderModel",
    "ProviderPolicyError",
    "ProviderRequestAttempt",
    "ProviderSettings",
    "ProviderTimeoutError",
    "RequestEstimate",
    "RetryPolicy",
    "UnavailableVisionProvider",
    "VisionCapabilities",
    "VisionProvider",
    "VisionProviderHub",
    "VisionProviderRegistry",
]
